# Generated by Django 3.2.23 on 2024-01-10 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DnaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64, verbose_name='文件名')),
                ('suffix_name', models.CharField(max_length=16, verbose_name='文件后缀')),
                ('content_type', models.CharField(max_length=16, verbose_name='文件类型')),
                ('bit_size', models.IntegerField(verbose_name='DNA大小')),
                ('segment_length', models.IntegerField(verbose_name='片段长度')),
                ('index_length', models.IntegerField(verbose_name='索引长度')),
                ('total_count', models.IntegerField(verbose_name='解码包数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dna_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DNA信息',
                'db_table': 'dna_info',
            },
        ),
        migrations.AddConstraint(
            model_name='dnainfo',
            constraint=models.UniqueConstraint(fields=('user', 'file_name'), name='unique_user_file_name'),
        ),
    ]
