# Generated by Django 3.2.23 on 2024-01-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnainfo',
            name='prime_segment_length',
            field=models.IntegerField(default=0, help_text='编码页面输入的片段长度', verbose_name='最初片段长度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dnainfo',
            name='segment_length',
            field=models.IntegerField(help_text='这是加入索引纠错的长度', verbose_name='片段长度'),
        ),
    ]
